### ISSUE TITLE
snap does not host latest jbang version

### ISSUE THREAD

**Issue by 38leinaD** [jbangdev/jbang-snap#1]
Hi,
I just installed snap on a raspberry pi and then downloaded jbang with it. The version that was installed is 0.52.1.
Is there a reason why the latest jbang version is not uploaded to snap?

Thanks,
Daniel

**Comment by maxandersen** [comment]
It's not updated as after it took months before snap allowed it in I didn't have time to find a way to do fully automated releases. At the moment its releases was done by hand. 

I'll see if I can remember / find how to make it automated. 

If anyone knows how I would appreciate pointers/PRs :)

**Comment by maxandersen** [comment]
for now I've updated snap manually to latest 0.66.1 - so your firestarter should work! :)

**Comment by sixcorners** [comment]
> If anyone knows how I would appreciate pointers/PRs :)

Made #2 for you. Thanks for jbang!
